site_name: MBON Marine Biodiversity Dashboard
site_description: Interactive dashboard for exploring marine acoustic monitoring data and acoustic indices analysis
site_author: MBON USC 2025 Project
repo_url: https://github.com/Waveform-Analytics/mbon-dash-2025/
repo_name: mbon-dash-2025
docs_dir: docs_site
site_dir: site

theme:
  name: material
  palette:
    # Ocean-themed colors matching your dashboard
    - scheme: default
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mermaid2
  - git-revision-date-localized:
      enable_creation_date: true
      type: date

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html

nav:
  - Overview: index.md
  - For Scientists: scientists.md
  - For Developers: developers.md
  - Data Structure: data.md
  - Interactive Notebooks: notebooks.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Waveform-Analytics/mbon-dash-2025/