# Species Filter Configuration
# Only these species will be included in the analysis and dashboard views
# All other species from the raw data will be filtered out during processing

keep_species:
  # Fish species
  - "sp"      # Silver perch  
  - "bd"      # Black drum
  - "otbw"    # Oyster toadfish boat whistle
  - "ss"      # Spotted seatrout
  - "rd"      # Red drum
  
  # Marine mammal sounds
  - "bde"     # Bottlenose dolphin echolocation
  - "bdbp"    # Bottlenose dolphin burst pulses  
  - "bdw"     # Bottlenose dolphin whistles
  
  # Anthropogenic sounds
  - "vessel"  # Vessels

# Notes:
# - This configuration is applied during data processing, raw data remains unchanged
# - To modify the species list, update this file and regenerate views
# - Use short codes as defined in data/raw/metadata/det_column_names.csv