[project]
name = "python"
version = "0.1.0"
description = "Acoustic indices and soundscapes - ESONS dataset"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "marimo>=0.15.2",
    "numpy>=2.3.2",
    "pandas>=2.3.2",
    "scipy>=1.16.1",
]
